'use strict';
let locale='es',currentCase='casa';
const cases={
casa:{solution:'Humanoide',es:['04 / TU CASA','Ayuda con la limpieza de tu casa','Cuéntale qué piso limpiar, en qué orden y a qué hora. Puedes mostrarlo con un video.',['Habitaciones y superficies que debe limpiar.','Herramientas y productos que puede usar.','Una sola visita o una rutina frecuente.']],en:['04 / YOUR HOME','Help with cleaning your home','Tell it which floor to clean, in what order and at what time. You can show it with a video.',['Rooms and surfaces to clean.','Tools and products it may use.','One visit or a regular routine.']],instruction:{es:'Quiero que limpies el piso de la sala. Empieza cerca de la ventana y termina en la puerta. Te muestro cómo en este video.',en:'Clean the living room floor. Start near the window and finish at the door. I will show you how in this video.'}},
limpieza:{solution:'Humanoide',es:['01 / RESTAURANTE','Una rutina de limpieza para tu restaurante','Describe qué superficies debe limpiar el robot, con qué herramientas y en qué horario.',['Superficies y orden de limpieza.','Herramientas y productos permitidos.','Horario y límites del área de trabajo.']],en:['01 / RESTAURANT','A cleaning routine for your restaurant','Describe which surfaces the robot should clean, the tools and the schedule.',['Surfaces and cleaning order.','Allowed tools and cleaning products.','Schedule and work-area limits.']],instruction:{es:'Limpia el lavamanos y las superficies del baño del restaurante. Sigue el orden que muestro en el video y trabaja dentro del área asignada.',en:'Clean the sink and restroom surfaces. Follow the order shown in the video and stay within the assigned area.'}},
parqueadero:{solution:'Humanoide',es:['02 / PARQUEADERO','Un robot celador para tu parqueadero','Explica qué recorrido debe seguir, qué puntos debe observar y a quién debe reportar una novedad.',['Ruta y puntos de observación.','Horarios, zonas permitidas y límites.','Situaciones que debe reportar a tu equipo.']],en:['02 / PARKING FACILITY','A parking security robot','Explain the route, the observation points and who should receive incident reports.',['Route and observation points.','Schedule, permitted zones and limits.','Situations to report to your team.']],instruction:{es:'Recorre el parqueadero por la ruta que muestro en el video. Observa los puntos indicados y reporta las novedades al equipo responsable.',en:'Patrol the parking facility along the route shown in the video. Observe the indicated points and report incidents to the responsible team.'}},
empaque:{solution:'Humanoide',es:['03 / FÁBRICA','Una secuencia de empaque en tu fábrica','Muestra cómo tomar el producto, colocarlo en la caja y comprobar el resultado antes de pasar al siguiente.',['Producto, dimensiones y peso.','Tipo de caja y orden de empaque.','Puesto de trabajo y resultado esperado.']],en:['03 / FACTORY','A packing sequence for your factory','Show how to pick up the product, place it in the box and check the result before moving to the next item.',['Product, dimensions and weight.','Box type and packing order.','Workstation and expected result.']],instruction:{es:'Toma cada producto y colócalo en la caja siguiendo la secuencia del video. Comprueba la posición antes de continuar con la siguiente unidad.',en:'Pick up each product and place it in the box following the video sequence. Check its position before continuing with the next unit.'}}
};
const tabs=[...document.querySelectorAll('[data-case]')];
document.querySelectorAll('[data-en]').forEach(e=>e.dataset.es=e.innerHTML);
const task=document.getElementById('task');task.dataset.placeholderEs=task.placeholder;
function showCase(key){currentCase=key;document.getElementById('app-instruction').textContent=cases[key].instruction[locale];const c=cases[key][locale];document.getElementById('case-meta').textContent=c[0];document.getElementById('case-title').textContent=c[1];document.getElementById('case-description').textContent=c[2];document.getElementById('case-requirements').replaceChildren(...c[3].map(t=>{const li=document.createElement('li');li.textContent=t;return li;}));document.getElementById('case-panel').setAttribute('aria-labelledby','tab-'+key);tabs.forEach(t=>{const active=t.dataset.case===key;t.setAttribute('aria-selected',String(active));t.tabIndex=active?0:-1;});}
tabs.forEach((t,i)=>{t.addEventListener('click',()=>showCase(t.dataset.case));t.addEventListener('keydown',e=>{let n;if(e.key==='ArrowRight')n=(i+1)%tabs.length;if(e.key==='ArrowLeft')n=(i+tabs.length-1)%tabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=tabs.length-1;if(n!==undefined){e.preventDefault();tabs[n].focus();showCase(tabs[n].dataset.case);}});});
const form=document.getElementById('quote-form'),messageLink=document.getElementById('message-link'),status=document.getElementById('form-status');
function resetMessage(){messageLink.hidden=true;messageLink.removeAttribute('href');status.textContent='';}
function chooseSolution(value,text){document.getElementById('solution').value=value;if(text)task.value=text;resetMessage();document.getElementById('cotizar').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});document.getElementById('name').focus({preventScroll:true});}
document.querySelectorAll('[data-solution]').forEach(b=>b.addEventListener('click',()=>chooseSolution(b.dataset.solution)));
document.getElementById('case-quote').addEventListener('click',()=>chooseSolution(cases[currentCase].solution,(locale==='es'?'Quiero ayuda con: ':'I want help with: ')+cases[currentCase][locale][1]+'. '));
const menu=document.getElementById('menu'),nav=document.getElementById('navigation');function closeMenu(){menu.setAttribute('aria-expanded','false');nav.classList.remove('open');}menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open);});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&menu.getAttribute('aria-expanded')==='true'){closeMenu();menu.focus();}});
function buildMessage(d,lang){const es=lang==='es';return [(es?'Quiero mi robot - Cognition Industries':'I want my robot - Cognition Industries'),'',(es?'Nombre: ':'Name: ')+d.name,(es?'Empresa: ':'Company: ')+(d.company||(es?'Uso personal':'Personal use')),(es?'País: ':'Country: ')+d.country,(es?'Solución: ':'Solution: ')+d.solution,(es?'Compra o alquiler: ':'Buy or rent: ')+(d.mode||''),(es?'Frecuencia: ':'Frequency: ')+(d.frequency||''),'',(es?'Tarea o repuesto: ':'Task or spare part: ')+d.task].join('\n');}
form.addEventListener('submit',e=>{e.preventDefault();if(!form.reportValidity())return;const d=Object.fromEntries([...new FormData(form)].map(([k,v])=>[k,String(v).trim()]));if(!d.name||d.task.length<10){status.textContent=locale==='es'?'Completa tu nombre y una descripción de al menos 10 caracteres.':'Enter your name and a description of at least 10 characters.';return;}messageLink.href='https://wa.me/17543006570?text='+encodeURIComponent(buildMessage(d,locale));messageLink.hidden=false;status.textContent=locale==='es'?'Tu solicitud está preparada. Abre WhatsApp para revisarla y enviarla.':'Your request is prepared. Open WhatsApp to review and send it.';messageLink.focus();});form.addEventListener('input',resetMessage);form.addEventListener('change',resetMessage);
document.getElementById('language').addEventListener('click',()=>{locale=locale==='es'?'en':'es';document.documentElement.lang=locale;document.querySelectorAll('[data-en]').forEach(e=>e.innerHTML=e.dataset[locale]);task.placeholder=task.dataset[locale==='es'?'placeholderEs':'placeholderEn'];const b=document.getElementById('language');b.textContent=locale==='es'?'EN':'ES';b.setAttribute('aria-label',locale==='es'?'Switch to English':'Cambiar a español');nav.setAttribute('aria-label',locale==='es'?'Navegación principal':'Main navigation');document.querySelectorAll('[data-legal-link]').forEach(a=>{const u=new URL(a.getAttribute('href'),location.href);u.search=locale==='en'?'?lang=en':'';a.href=u.href;});document.title=locale==='es'?'Cognition Industries | Robótica y Cloud IA en Latinoamérica':'Cognition Industries | Robotics and AI Cloud in Latin America';resetMessage();showCase(currentCase);});showCase(currentCase);

if(document.modelContext?.registerTool){
 const lifecycle=new AbortController();
 const tool={name:'prepare_quote_request',title:'Preparar solicitud de cotización',description:'Fill the visible quotation form and prepare its WhatsApp link. Does not send a message, purchase a robot or submit data to a server.',inputSchema:{type:'object',properties:{name:{type:'string',minLength:1,maxLength:100},company:{type:'string',minLength:1,maxLength:120},country:{type:'string'},solution:{type:'string',enum:['Humanoide','Cuadrúpedo','Cloud IA','Repuestos','Hardware + Cloud IA']},task:{type:'string',minLength:10,maxLength:1200},mode:{type:'string',enum:['Comprar','Alquilar','Quiero orientación']},frequency:{type:'string',enum:['Tarea permanente','Tarea puntual','Por definir']}},required:['name','company','country','solution','task'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){
  if(!input||typeof input!=='object')throw new Error('Invalid quote request');
  const limits={name:100,company:120,country:100,solution:100,task:1200};const values={};
  for(const key of Object.keys(limits)){if(typeof input[key]!=='string'||!input[key].trim()||input[key].trim().length>limits[key])throw new Error('Invalid '+key);values[key]=input[key].trim();}
  if(values.task.length<10)throw new Error('Task description is too short');
  for(const key of ['country','solution']){if(![...document.getElementById(key).options].some(o=>o.value===values[key]&&o.value))throw new Error('Unsupported '+key);}
  for(const key of ['mode','frequency']){const v=input[key]||(key==='mode'?'Quiero orientación':'Por definir');if(![...document.getElementById(key).options].some(o=>o.value===v&&v))throw new Error('Unsupported '+key);values[key]=v;}
  for(const key of Object.keys(values))document.getElementById(key).value=values[key];
  form.requestSubmit();document.getElementById('cotizar').scrollIntoView();
  return {status:'prepared',whatsapp_url:messageLink.href,message_sent:false};
 }};
 try{Promise.resolve(document.modelContext.registerTool(tool,{signal:lifecycle.signal})).catch(()=>{});}catch(e){}
 window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});
}

document.querySelectorAll('[data-case-pick]').forEach(b=>b.addEventListener('click',()=>{showCase(b.dataset.casePick);document.getElementById('case-panel').scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth',block:'center'});document.getElementById('case-panel').focus({preventScroll:true});}));
const openingFilm=document.getElementById('opening-film');
if(openingFilm&&window.matchMedia('(prefers-reduced-motion: reduce)').matches){openingFilm.autoplay=false;openingFilm.removeAttribute('autoplay');openingFilm.pause();}
